#Silahkan anda modifikasi script ini
#Tapi jangan anda rubah credit di script ini
#Belajarlah menghargai orang lain
#Author : Smallker
try:
    print '''
    |------------------------------------------------|
    | Coded by Smallker, visit http://www.smallker.cf|
    |------------------------------------------------|'''
    print '''            
      ____                  _ _ _                      
     / ___| _ __ ___   __ _| | | | ___ __ ___ ________ 
     \___ \| '_ ` _ \ / _` | | | |/ / '__/ _ \_  /_  / 
      ___) | | | | | | (_| | | |   <| | |  __// / / /  
     |____/|_| |_| |_|\__,_|_|_|_|\_\_|  \___/___/___|

                 User Password Profilling'''
    print "\n"
    print "\n"
    nama_file = raw_input("    Please enter the output file : ")
    word = open(nama_file,'a+')
    print "\n"
    print "    Enter the word that will be randomize"
    a = raw_input('    first word : ')
    b = raw_input('    second word : ')
    c = raw_input('    third word : ')
    d = raw_input('    fourth word : ')
    e = raw_input('    fifth word : ')
    f = raw_input('    sixth word : ')
    g = raw_input('    seventh word : ')
    word.write(a)
    word.write('\n')
    word.write(b)
    word.write('\n')
    word.write(c)
    word.write('\n')
    word.write(d)
    word.write('\n')
    word.write(e)
    word.write('\n')
    word.write(f)
    word.write('\n')
    word.write(a + b)
    word.write('\n')
    word.write(a + c)
    word.write('\n')
    word.write(a + d)
    word.write('\n')
    word.write(a + e)
    word.write('\n')
    word.write(a + f)
    word.write('\n')
    word.write(a + g)
    word.write('\n')
    word.write(b + a)
    word.write('\n')
    word.write(b + c)
    word.write('\n')
    word.write(b + d)
    word.write('\n')
    word.write(b + e)
    word.write('\n')
    word.write(b + f)
    word.write('\n')
    word.write(b + g)
    word.write('\n')
    word.write(c + a)
    word.write('\n')
    word.write(c + b)
    word.write('\n')
    word.write(c + d)
    word.write('\n')
    word.write(c + e)
    word.write('\n')
    word.write(c + f)
    word.write('\n')
    word.write(c + g)
    word.write('\n')
    word.write(d + a)
    word.write('\n')
    word.write(d + b)
    word.write('\n')
    word.write(d + c)
    word.write('\n')
    word.write(d + e)
    word.write('\n')
    word.write(d + f)
    word.write('\n')
    word.write(d + g)
    word.write('\n')
    word.write(e + a)
    word.write('\n')
    word.write(e + b)
    word.write('\n')
    word.write(e + c)
    word.write('\n')
    word.write(e + d)
    word.write('\n')
    word.write(e + f)
    word.write('\n')
    word.write(e + g)
    word.write('\n')
    word.write(f + a)
    word.write('\n')
    word.write(f + b)
    word.write('\n')
    word.write(f + c)
    word.write('\n')
    word.write(f + d)
    word.write('\n')
    word.write(f + e)
    word.write('\n')
    word.write(f + g)
    word.write('\n')
    word.write(g + a)
    word.write('\n')
    word.write(g + b)
    word.write('\n')
    word.write(g + c)
    word.write('\n')
    word.write(g + d)
    word.write('\n')
    word.write(g + e)
    word.write('\n')
    word.write(g + f)
    word.write('\n')
    word.write(a + b + c)
    word.write('\n')
    word.write(a + b + d)
    word.write('\n')
    word.write(a + b + e)
    word.write('\n')
    word.write(a + b + f)
    word.write('\n')
    word.write(a + b + g)
    word.write('\n')
    word.write(a + c + b)
    word.write('\n')
    word.write(a + c + d)
    word.write('\n')
    word.write(a + c + e)
    word.write('\n')
    word.write(a + c + f)
    word.write('\n')
    word.write(a + c + g)
    word.write('\n')
    word.write(a + d + b)
    word.write('\n')
    word.write(a + d + c)
    word.write('\n')
    word.write(a + d + e)
    word.write('\n')
    word.write(a + d + f)
    word.write('\n')
    word.write(a + d + g)
    word.write('\n')
    word.write(a + e + b)
    word.write('\n')
    word.write(a + e + c)
    word.write('\n')
    word.write(a + e + d)
    word.write('\n')
    word.write(a + e + f)
    word.write('\n')
    word.write(a + e + g)
    word.write('\n')
    word.write(b + a + c)
    word.write('\n')
    word.write(b + a + d)
    word.write('\n')
    word.write(b + a + e)
    word.write('\n')
    word.write(b + a + f)
    word.write('\n')
    word.write(b + a + g)
    word.write('\n')
    word.write(b + c + a)
    word.write('\n')
    word.write(b + c + d)
    word.write('\n')
    word.write(b + c + e)
    word.write('\n')
    word.write(b + c + f)
    word.write('\n')
    word.write(b + c + g)
    word.write('\n')
    word.write(b + d + a)
    word.write('\n')
    word.write(b + d + c)
    word.write('\n')
    word.write(b + d + e)
    word.write('\n')
    word.write(b + d + f)
    word.write('\n')
    word.write(b + d + g)
    word.write('\n')
    word.write(b + e + a)
    word.write('\n')
    word.write(b + e + c)
    word.write('\n')
    word.write(b + e + d)
    word.write('\n')
    word.write(b + e + f)
    word.write('\n')
    word.write(b + e + g)
    word.write('\n')
    word.write(c + a + b)
    word.write('\n')
    word.write(c + a + d)
    word.write('\n')
    word.write(c + a + e)
    word.write('\n')
    word.write(c + a + f)
    word.write('\n')
    word.write(c + a + g)
    word.write('\n')
    word.write(c + b + a)
    word.write('\n')
    word.write(c + b + d)
    word.write('\n')
    word.write(c + b + e)
    word.write('\n')
    word.write(c + b + f)
    word.write('\n')
    word.write(c + b + g)
    word.write('\n')
    word.write(c + d + a)
    word.write('\n')
    word.write(c + d + b)
    word.write('\n')
    word.write(c + d + e)
    word.write('\n')
    word.write(c + d + f)
    word.write('\n')
    word.write(c + d + g)
    word.write('\n')
    word.write(c + e + a)
    word.write('\n')
    word.write(c + e + b)
    word.write('\n')
    word.write(c + e + d)
    word.write('\n')
    word.write(c + e + f)
    word.write('\n')
    word.write(c + e + g)
    word.write('\n')
    word.write(d + a + b)
    word.write('\n')
    word.write(d + a + c)
    word.write('\n')
    word.write(d + a + e)
    word.write('\n')
    word.write(d + a + f)
    word.write('\n')
    word.write(d + a + g)
    word.write('\n')
    word.write(d + b + a)
    word.write('\n')
    word.write(d + b + c)
    word.write('\n')
    word.write(d + b + e)
    word.write('\n')
    word.write(d + b + f)
    word.write('\n')
    word.write(d + b + g)
    word.write('\n')
    word.write(d + c + a)
    word.write('\n')
    word.write(d + c + b)
    word.write('\n')
    word.write(d + c + e)
    word.write('\n')
    word.write(d + c + f)
    word.write('\n')
    word.write(d + c + g)
    word.write('\n')
    word.write(d + e + a)
    word.write('\n')
    word.write(d + e + b)
    word.write('\n')
    word.write(d + e + c)
    word.write('\n')
    word.write(d + e + f)
    word.write('\n')
    word.write(d + e + g)
    word.write('\n')
    word.write(e + a + b)
    word.write('\n')
    word.write(e + a + c)
    word.write('\n')
    word.write(e + a + d)
    word.write('\n')
    word.write(e + a + f)
    word.write('\n')
    word.write(e + a + g)
    word.write('\n')
    word.write(e + b + a)
    word.write('\n')
    word.write(e + b + c)
    word.write('\n')
    word.write(e + b + d)
    word.write('\n')
    word.write(e + b + f)
    word.write('\n')
    word.write(e + b + g)
    word.write('\n')
    word.write(e + c + a)
    word.write('\n')
    word.write(e + c + b)
    word.write('\n')
    word.write(e + c + d)
    word.write('\n')
    word.write(e + c + f)
    word.write('\n')
    word.write(e + c + g)
    word.write('\n')
    word.write(e + d + a)
    word.write('\n')
    word.write(e + d + b)
    word.write('\n')
    word.write(e + d + c)
    word.write('\n')
    word.write(e + d + f)
    word.write('\n')
    word.write(e + d + g)
    word.write('\n')
    word.write(f + a + b)
    word.write('\n')
    word.write(f + a + c)
    word.write('\n')
    word.write(f + a + d)
    word.write('\n')
    word.write(f + a + e)
    word.write('\n')
    word.write(f + a + g)
    word.write('\n')
    word.write(f + b + a)
    word.write('\n')
    word.write(f + b + c)
    word.write('\n')
    word.write(f + b + d)
    word.write('\n')
    word.write(f + b + e)
    word.write('\n')
    word.write(f + b + g)
    word.write('\n')
    word.write(f + c + a)
    word.write('\n')
    word.write(f + c + b)
    word.write('\n')
    word.write(f + c + d)
    word.write('\n')
    word.write(f + c + e)
    word.write('\n')
    word.write(f + c + g)
    word.write('\n')
    word.write(f + d + a)
    word.write('\n')
    word.write(f + d + b)
    word.write('\n')
    word.write(f + d + c)
    word.write('\n')
    word.write(f + d + e)
    word.write('\n')
    word.write(f + d + g)
    word.write('\n')
    word.write(g + a + b)
    word.write('\n')
    word.write(g + a + c)
    word.write('\n')
    word.write(g + a + d)
    word.write('\n')
    word.write(g + a + e)
    word.write('\n')
    word.write(g + a + f)
    word.write('\n')
    word.write(g + b + a)
    word.write('\n')
    word.write(g + b + c)
    word.write('\n')
    word.write(g + b + d)
    word.write('\n')
    word.write(g + b + e)
    word.write('\n')
    word.write(g + b + f)
    word.write('\n')
    word.write(g + c + a)
    word.write('\n')
    word.write(g + c + b)
    word.write('\n')
    word.write(g + c + d)
    word.write('\n')
    word.write(g + c + e)
    word.write('\n')
    word.write(g + c + f)
    word.write('\n')
    word.write(g + d + a)
    word.write('\n')
    word.write(g + d + b)
    word.write('\n')
    word.write(g + d + c)
    word.write('\n')
    word.write(g + d + e)
    word.write('\n')
    word.write(g + d + f)
    word.write('\n')
    word.write(g + e + a)
    word.write('\n')
    word.write(g + e + b)
    word.write('\n')
    word.write(g + e + c)
    word.write('\n')
    word.write(g + e + d)
    word.write('\n')
    word.write(g + e + f)
    word.write('\n')
    word.write(g + f + a)
    word.write('\n')
    word.write(g + f + b)
    word.write('\n')
    word.write(g + f + c)
    word.write('\n')
    word.write(g + f + d)
    word.write('\n')
    word.write(g + f + e)
    print '''
    |------------------------|
    |Wordlist write done !!!!|
    |------------------------|
     File saved as ''' + nama_file
except KeyboardInterrupt:
    print '''
    |----------------------------------|
    | You have aborted the operation !!|
    |----------------------------------|
    '''
